"""External validation: hold the decoders to a file a real compiler wrote.

Every other fixture here was generated by this repository, which proves the
decoders are self-consistent and cannot prove they match a compiler. This one
compiles COBOL with GnuCOBOL and reads what comes out.

Skipped when cobc is absent - `sudo apt-get install gnucobol` to run it.
"""

from __future__ import annotations

import shutil
import tempfile
from pathlib import Path

import pytest

pytestmark = pytest.mark.skipif(
    not shutil.which("cobc"),
    reason="install gnucobol to run the external validation")


def test_every_decoder_agrees_with_a_real_compiler():
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
    from validate_with_gnucobol import Unavailable, validate

    with tempfile.TemporaryDirectory() as td:
        try:
            results = validate(Path(td))
        except Unavailable as exc:
            pytest.skip(str(exc))
    failed = [msg for ok, msg in results if not ok]
    assert not failed, "\n".join(failed)
    assert len(results) >= 10, f"only {len(results)} checks ran"
