"""Targets generated FROM a plan - never from a copybook directly.

Everything here is a rendering of decisions already made and recorded. If a
decision is still open, nothing is rendered: `require_resolved` raises and names
what is missing. A schema that silently picked for you is worse than no schema,
because it looks finished.
"""

from __future__ import annotations

import json

from .plan import PlanError, require_resolved

_JSON_TYPES = (
    ("VARCHAR", "string"), ("CHAR", "string"), ("BYTEA", "string"),
    ("NUMERIC", "number"), ("REAL", "number"), ("DOUBLE", "number"),
    ("SMALLINT", "integer"), ("INTEGER", "integer"), ("BIGINT", "integer"),
)


def _resolutions(plan: dict) -> dict:
    return {u["id"]: u.get("resolution") for u in plan["unresolved"]}


def postgres_ddl(plan: dict) -> str:
    require_resolved(plan)
    res = _resolutions(plan)
    pk = (res.get("primary_key") or {}).get("primary_key") or []
    pk_cols = [_col_name(plan, f) for f in pk]

    out: list[str] = [
        f"-- generated by overpunch from {plan['source']['copybook']}",
        f"-- {plan['source']['record_bytes']}-byte fixed records, "
        f"{plan['source']['encoding']}",
        f"-- policies: {json.dumps(plan['policies'])}",
        "",
    ]
    for t in plan["tables"]:
        out.append(f"CREATE TABLE {t['name']} (")
        # (sql, trailing comment) kept apart so the separating comma is never
        # swallowed by a comment - which produced DDL that would not parse
        rows: list[tuple[str, str]] = []
        if t["kind"] == "occurs":
            rows.append(("    " + _pad("parent_id") + "BIGINT NOT NULL", ""))
            rows.append(("    " + _pad("occurrence") + "SMALLINT NOT NULL", ""))
        for c in t["columns"]:
            nn = " NOT NULL" if c["name"] in pk_cols else ""
            rows.append(("    " + _pad(c["name"]) + c["type"] + nn, c["note"]))
        if t["kind"] == "root" and pk_cols:
            rows.append((f"    PRIMARY KEY ({', '.join(pk_cols)})", ""))
        if t["kind"] == "occurs":
            rows.append(("    PRIMARY KEY (parent_id, occurrence)", ""))
        for i, (sql, comment) in enumerate(rows):
            sep = "," if i < len(rows) - 1 else ""
            out.append(sql + sep + (f"  -- {comment}" if comment else ""))
        out.append(");")
        if t["kind"] == "occurs":
            out.append(f"-- {t['occurs_of']} OCCURS up to {t['occurs_max']}"
                       + (f" DEPENDING ON {t['depends_on']}" if t["depends_on"] else ""))
        out.append("")
    return "\n".join(out)


def _pad(name: str, width: int = 26) -> str:
    return name.ljust(width)


def _col_name(plan: dict, cobol_name: str) -> str:
    for t in plan["tables"]:
        for c in t["columns"]:
            if c["field"].upper() == cobol_name.upper():
                return c["name"]
    return cobol_name.lower().replace("-", "_")


def json_schema(plan: dict) -> str:
    require_resolved(plan)
    root = plan["tables"][0]
    props = {c["name"]: {"type": _json_type(c["type"]),
                         "x-cobol-field": c["field"],
                         "x-offset": c["offset"], "x-bytes": c["bytes"]}
             for c in root["columns"]}
    for t in plan["tables"][1:]:
        props[t["name"].replace(root["name"] + "_", "")] = {
            "type": "array", "maxItems": t["occurs_max"],
            "items": {"type": "object",
                      "properties": {c["name"]: {"type": _json_type(c["type"])}
                                     for c in t["columns"]}}}
    return json.dumps({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": root["name"],
        "description": f"generated by overpunch from {plan['source']['copybook']}",
        "type": "object", "properties": props,
    }, indent=2)


def _json_type(sql: str) -> str:
    up = sql.upper()
    for prefix, js in _JSON_TYPES:
        if up.startswith(prefix):
            return js
    return "string"


def loader_script(plan: dict, data_path: str = "records.csv") -> str:
    require_resolved(plan)
    root = plan["tables"][0]
    cols = ", ".join(c["name"] for c in root["columns"])
    return "\n".join([
        "#!/bin/sh",
        "# generated by overpunch - decode, then load.",
        "set -eu",
        "",
        f"overpunch decode {plan['source']['copybook']} \"$1\" \\",
        f"    --encoding {plan['source']['encoding']} -o {data_path}",
        "",
        f"psql \"$DATABASE_URL\" -c \"\\\\copy {root['name']} ({cols}) "
        f"FROM '{data_path}' WITH (FORMAT csv, HEADER true)\"",
        "",
    ])
