"""Validate the decoders against a file a REAL COBOL COMPILER wrote.

Every other fixture in this repository was generated by this repository. That
proves the decoders are self-consistent; it cannot prove they match what a
compiler actually emits, because both halves come from the same understanding.
This script closes that loop: it compiles a COBOL program with GnuCOBOL, runs
it, and holds overpunch to the bytes that come out.

    sudo apt-get install gnucobol
    python scripts/validate_with_gnucobol.py

It found a real defect the day it was written. GnuCOBOL on x86 writes COMP-1 and
COMP-2 in NATIVE byte order, and overpunch read only network order - so it named
the format correctly, got the byte order wrong, and reported FLOAT_FORMAT_CONFIRMED
over values like 1.16e-53 where the truth was 1.727.
"""
from __future__ import annotations

import shutil
import struct
import subprocess
import sys
import tempfile
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from overpunch.copybook import parse                      # noqa: E402
from overpunch.decode import decode_field                 # noqa: E402
from overpunch.findings import evaluate                   # noqa: E402
from overpunch.probe import iter_records, scan            # noqa: E402

RECORDS = 200

PROGRAM = '''\
       IDENTIFICATION DIVISION.
       PROGRAM-ID. GENFILE.
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT OUT-FILE ASSIGN TO "gnucobol.dat"
               ORGANIZATION IS SEQUENTIAL.
       DATA DIVISION.
       FILE SECTION.
       FD  OUT-FILE.
       01  OUT-REC.
           05  R-ID        PIC 9(06).
           05  R-AMOUNT    PIC S9(05)V99.
           05  R-PACKED    PIC S9(07)V99 COMP-3.
           05  R-BINARY    PIC S9(04)    COMP.
           05  R-SINGLE                  COMP-1.
           05  R-DOUBLE                  COMP-2.
       WORKING-STORAGE SECTION.
       01  I           PIC 9(06) VALUE 0.
       01  W-AMT       PIC S9(05)V99 VALUE 0.
       01  W-FLT       COMP-2 VALUE 0.
       01  W-SEED      PIC 9(05) VALUE 17.
       PROCEDURE DIVISION.
       MAIN-PARA.
           OPEN OUTPUT OUT-FILE
           COMPUTE W-FLT = FUNCTION RANDOM(W-SEED)
           PERFORM VARYING I FROM 1 BY 1 UNTIL I > %d
               COMPUTE W-AMT = FUNCTION RANDOM * 90000 + 1
               IF FUNCTION MOD(I, 3) = 0
                   COMPUTE W-AMT = 0 - W-AMT
               END-IF
               MOVE I     TO R-ID
               MOVE W-AMT TO R-AMOUNT
               MOVE W-AMT TO R-PACKED
               COMPUTE R-BINARY = FUNCTION MOD(I, 9000) - 4000
               COMPUTE W-FLT =
                   FUNCTION RANDOM * (10 ** FUNCTION MOD(I, 7)) + 0.5
               MOVE W-FLT TO R-SINGLE
               MOVE W-FLT TO R-DOUBLE
               WRITE OUT-REC
           END-PERFORM
           CLOSE OUT-FILE
           STOP RUN.
''' % RECORDS

COPYBOOK = '''\
000100* Written by GnuCOBOL, not by this repository.
000200 01  OUT-REC.
000300     05  R-ID        PIC 9(06).
000400     05  R-AMOUNT    PIC S9(05)V99.
000500     05  R-PACKED    PIC S9(07)V99 COMP-3.
000600     05  R-BINARY    PIC S9(04)    COMP.
000700     05  R-SINGLE    COMP-1.
000800     05  R-DOUBLE    COMP-2.
'''


class Unavailable(RuntimeError):
    pass


def build(workdir: Path) -> Path:
    """Compile and run the program; return the data file it wrote."""
    if not shutil.which("cobc"):
        raise Unavailable("GnuCOBOL (cobc) is not installed")
    (workdir / "genfile.cob").write_text(PROGRAM)
    run = subprocess.run(["cobc", "-x", "genfile.cob", "-o", "genfile"],
                         cwd=workdir, capture_output=True, text=True)
    if run.returncode:
        raise Unavailable(f"cobc failed: {run.stderr.strip()[:300]}")
    subprocess.run(["./genfile"], cwd=workdir, check=True, capture_output=True)
    data = workdir / "gnucobol.dat"
    if not data.exists() or not data.stat().st_size:
        raise Unavailable("the compiled program wrote nothing")
    return data


def validate(workdir: Path) -> list[tuple[bool, str]]:
    data = build(workdir)
    cpy = workdir / "GNUREC.cpy"
    cpy.write_text(COPYBOOK)
    layout = parse(COPYBOOK)
    raw = data.read_bytes()
    rlen = layout.record_length()
    out: list[tuple[bool, str]] = []

    def check(ok, msg):
        out.append((bool(ok), msg))

    check(len(raw) == RECORDS * rlen,
          f"the copybook's {rlen}-byte record divides the compiler's file "
          f"({len(raw):,} bytes, {RECORDS} records)")

    fields = {f.name: f for f in layout.elementary_fields()}
    rows = []
    for rec in iter_records(str(data), rlen, recfm="fixed"):
        rows.append({n: rec[f.offset:f.offset + f.total_size()]
                     for n, f in fields.items()})

    # 1. the ASCII-native sign convention, as the compiler writes it
    signs = {r["R-AMOUNT"][-1] for r in rows}
    negatives = {b for b in signs if not 0x30 <= b <= 0x39}
    check(negatives and all(0x70 <= b <= 0x79 for b in negatives),
          f"negative DISPLAY values end in 0x70-0x79 as claimed "
          f"(saw {len(negatives)} distinct: "
          f"{', '.join(hex(b) for b in sorted(negatives))})")

    # 2. two INDEPENDENT decoders on the same logical values. The compiler wrote
    #    the same number as zoned DISPLAY and as COMP-3; if the decoders agree
    #    record by record, they agree about something neither of them invented.
    disp = [decode_field(r["R-AMOUNT"], fields["R-AMOUNT"], "latin-1") for r in rows]
    packed = [decode_field(r["R-PACKED"], fields["R-PACKED"], "latin-1") for r in rows]
    check(disp == packed,
          f"the zoned-DISPLAY and COMP-3 decoders agree on all {len(rows)} "
          f"records (total {sum(disp):,})")
    check(any(v < 0 for v in disp),
          f"{sum(1 for v in disp if v < 0)} of {len(rows)} values are negative, "
          f"so the sign is actually being exercised")

    # 3. COMP, against the value the COBOL program computed
    binary = [decode_field(r["R-BINARY"], fields["R-BINARY"], "latin-1") for r in rows]
    expected = [Decimal((i + 1) % 9000 - 4000) for i in range(len(rows))]
    check(binary == expected,
          "COMP is big-endian: every value matches MOD(I,9000)-4000")

    # 4. floats: the byte order the compiler actually used
    stats = scan(str(data), layout, encoding="latin-1", float_format="hfp")
    codes = {(f.code, f.field) for f in evaluate(layout, stats)}
    check(("FLOAT_FORMAT_MISMATCH", "R-SINGLE") in codes
          and ("FLOAT_FORMAT_MISMATCH", "R-DOUBLE") in codes,
          "read as hex float, both COMP-1 and COMP-2 are REFUSED, not decoded")

    stats_le = scan(str(data), layout, encoding="latin-1", float_format="ieee-le")
    codes_le = {(f.code, f.field) for f in evaluate(layout, stats_le)}
    check(("FLOAT_FORMAT_CONFIRMED", "R-SINGLE") in codes_le
          and ("FLOAT_FORMAT_CONFIRMED", "R-DOUBLE") in codes_le,
          "read as little-endian IEEE, both are CONFIRMED")
    check(not any(c == "FLOAT_FORMAT_CONFIRMED" for c, _ in codes),
          "and the WRONG reading is never confirmed")

    # 5. the values themselves: COMP-1 and COMP-2 hold the same number, so the
    #    two widths must agree to single precision. A byte order that were still
    #    wrong could not satisfy this.
    singles = [decode_field(r["R-SINGLE"], fields["R-SINGLE"], "latin-1", "ieee-le")
               for r in rows]
    doubles = [decode_field(r["R-DOUBLE"], fields["R-DOUBLE"], "latin-1", "ieee-le")
               for r in rows]
    close = sum(1 for a, b in zip(singles, doubles)
                if b != 0 and abs((a - b) / b) < Decimal("1e-6"))
    check(close == len(rows),
          f"COMP-1 and COMP-2 hold the same value to single precision in "
          f"{close}/{len(rows)} records")
    check(all(v.is_finite() and abs(v) < 10 ** 7 for v in doubles),
          "and every decoded double is a plausible magnitude, not 1e+41")
    return out


def main() -> int:
    with tempfile.TemporaryDirectory() as td:
        try:
            results = validate(Path(td))
        except Unavailable as exc:
            print(f"SKIP: {exc}")
            print("      install it with: sudo apt-get install gnucobol")
            return 0
    bad = 0
    print("overpunch vs. a file GnuCOBOL actually wrote\n")
    for ok, msg in results:
        print(f"  [{'PASS' if ok else 'FAIL'}] {msg}")
        bad += not ok
    print(f"\n{len(results) - bad} passed, {bad} failed")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
