/* Render PostgreSQL DDL from a plan, in the browser.

   A second implementation of postgres_ddl() in src/overpunch/generate.py.
   page/verify_js.js requires the two to agree byte for byte.

   It exists so the primary key can be CHOSEN on the page - including a composite
   one, which is what a VSAM key usually is - rather than substituted into
   pre-rendered text. The first version patched the key line with a regex and
   could only express a single column, which quietly made the wrong answer the
   only expressible one. */
var DDL = (function(){
"use strict";

/* Python's json.dumps writes ", " and ": " separators; JSON.stringify writes
   neither. The page states this DDL is real tool output, so it has to be the
   same bytes, down to the spacing in a comment. */
function pyJson(v){
  if(v === null) return "null";
  if(Array.isArray(v)) return "[" + v.map(pyJson).join(", ") + "]";
  if(typeof v === "object") return "{" + Object.keys(v).map(function(k){
      return JSON.stringify(k) + ": " + pyJson(v[k]); }).join(", ") + "}";
  return JSON.stringify(v);
}

function pad(name){ while(name.length < 26) name += " "; return name; }

/* A second implementation of postgres_ddl() from src/overpunch/generate.py.
   page/verify_ddl.js requires the two to agree byte for byte; it exists so the
   primary key can be chosen here, including a composite one, rather than being
   substituted into pre-rendered text. */
function render(p, pkFields){
  var plan = p.plan, pkCols = (pkFields||[]).map(columnName.bind(null, plan));
  var out = ["-- generated by overpunch from " + plan.source.copybook,
             "-- " + plan.source.record_bytes + "-byte fixed records, " +
             plan.source.encoding,
             "-- policies: " + pyJson(plan.policies), ""];
  plan.tables.forEach(function(t){
    out.push("CREATE TABLE " + t.name + " (");
    var rows = [];
    if(t.kind === "occurs"){
      rows.push(["    " + pad("parent_id") + "BIGINT NOT NULL", ""]);
      rows.push(["    " + pad("occurrence") + "SMALLINT NOT NULL", ""]);
    }
    t.columns.forEach(function(c){
      var nn = pkCols.indexOf(c.name) >= 0 ? " NOT NULL" : "";
      rows.push(["    " + pad(c.name) + c.type + nn, c.note]);
    });
    if(t.kind === "root" && pkCols.length)
      rows.push(["    PRIMARY KEY (" + pkCols.join(", ") + ")", ""]);
    if(t.kind === "occurs")
      rows.push(["    PRIMARY KEY (parent_id, occurrence)", ""]);
    rows.forEach(function(r, i){
      out.push(r[0] + (i < rows.length - 1 ? "," : "") + (r[1] ? "  -- " + r[1] : ""));
    });
    out.push(");");
    if(t.kind === "occurs")
      out.push("-- " + t.occurs_of + " OCCURS up to " + t.occurs_max +
               (t.depends_on ? " DEPENDING ON " + t.depends_on : ""));
    out.push("");
  });
  return out.join("\n");
}
function columnName(plan, cobolName){
  for(var i=0;i<plan.tables.length;i++)
    for(var j=0;j<plan.tables[i].columns.length;j++)
      if(plan.tables[i].columns[j].field.toUpperCase() === cobolName.toUpperCase())
        return plan.tables[i].columns[j].name;
  return cobolName.toLowerCase().replace(/-/g,"_");
}

return {render: render, columnName: columnName, pad: pad, pyJson: pyJson};
})();
